name: My Actions
on: push
jobs:
  build:
    name: Build and deploy to web server
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: yarn install
      - run: yarn test --watchAll=false
      - run: yarn build
      - run: rsync -avz -e 'ssh' build/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
